- name: Systems identified as Webservers and their variables
  hosts: web_servers
  #  gather_facts: no

  tasks:
    - name: Print out Variable Information for Webserver Group
      debug:
       var: hostvars[inventory_hostname]


- name: Systems identified as Load Balancers and their variables
  hosts: lb_servers
  gather_facts: no

  tasks:
    - name: Print out Variable Information for Load-Balancer Group
      debug:
       var: hostvars[inventory_hostname]
