---
- name: Playbook to Show Users
  hosts: all
  become: true

  tasks:
    - name: show ansible_user_id with BECOME=true
      debug:
        var: ansible_user_id

- name: Test ansible_user_id
  hosts: all
  become: false

  tasks:
    - name: show ansible_user_id with BECOME=false
      debug:
        var: ansible_user_id
